name: Update LeetCode Stats

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate LeetCode Stats Card
        run: |
          curl -o leetcode-stats.svg https://leetcard.jacoblin.cool/dhruv_bhrasadiya?theme=dark&font=baloo&ext=heatmap

      - name: Commit and push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add leetcode-stats.svg
          git commit -m "Update LeetCode stats" || exit 0
          git push
